Hw 1
Uberwald/ML_System_design pull request #1
Opened 2024-11-30 12:07 UTC by Uberwald

2024-12-04 09:21 UTC, Anzovi commented
Хорошоий дез док, cкоуп проекта определен. Понятно, что будет и что не будет закрыто в данной итерации. 
Корректировка: нужно поменять блок схему из шаблона на свою.

2024-12-04 20:34 UTC, THECODEDEMOGORGON commented
Что классно:
- Цель проекта понятная и измеримая, это круто - по ML постановке задачи также вопросов нет
- Технический способ решения тоже рабочий 

Что можно улучшить:
- Да, лучше докинуть хотя бы простенькую блок-схему решения
- Выровнять числа и определения (например где-то таргет это оформления карты в течение 14и дней, где-то в течение 21 дня). Момент важный т.к. влияет на циклы переобучения и обновления скоров модели.
- Тут вкусовщина, но это скорее look-alike модель нежели рекомендательная.
- По способу оценки пилота не совсем понятно - хотите взять пользователей за последние полгода, но при этом эти полгода перескаются с трейном модели (т.к. в тест берется только сентябрь). Очевидно увидим среднюю конверсию выше там где будет выше скор. Если речь о ретро-тесте, то лучше явно прописать что берете компании которые модель не видела и по ним смотрите. Но, как мне кажется, проще сразу описать запуск АБ теста, где контроль - сбор сегмента для коммуникации по текущему варианту; тест - по модели. Ведь ретро-теста вряд ли будет достаточно чтобы принять решение о сборе по модельны скорам всего сегмента для коммуникации.

2024-12-04 20:51 UTC, Uberwald commented
> Что классно:
> 
>     * Цель проекта понятная и измеримая, это круто - по ML постановке задачи также вопросов нет
> 
>     * Технический способ решения тоже рабочий
> 
> 
> Что можно улучшить:
> 
>     * Да, лучше докинуть хотя бы простенькую блок-схему решения
> 
>     * Выровнять числа и определения (например где-то таргет это оформления карты в течение 14и дней, где-то в течение 21 дня). Момент важный т.к. влияет на циклы переобучения и обновления скоров модели.
> 
>     * Тут вкусовщина, но это скорее look-alike модель нежели рекомендательная.
> 
>     * По способу оценки пилота не совсем понятно - хотите взять пользователей за последние полгода, но при этом эти полгода перескаются с трейном модели (т.к. в тест берется только сентябрь). Очевидно увидим среднюю конверсию выше там где будет выше скор. Если речь о ретро-тесте, то лучше явно прописать что берете компании которые модель не видела и по ним смотрите. Но, как мне кажется, проще сразу описать запуск АБ теста, где контроль - сбор сегмента для коммуникации по текущему варианту; тест - по модели. Ведь ретро-теста вряд ли будет достаточно чтобы принять решение о сборе по модельны скорам всего сегмента для коммуникации.

1) Всё правильно с 14 и 21 днями. Есть дата коммуникации, берется проверка в 21 день, есть ли дата контракта, если есть, то она становится бизнес датой. Потом уже берется граф звонков от этой бизнес даты в прошлое на 14 дней
2) Пилот будет проверятся не за полгода, а за тот период, который не участвовал в обучении, в том числе буде проведена проверка за какой-то один конкретный день: у нас уже есть обученная модель, которая по признакам может определить вероятность класса 1 или 0, поэтому просто берем ОДНУ бизнес дату (допустим 14 октября), собираем на неё фичи, а потом проверяем действительно ли предсказанные товарищи класса 1 оформили карточку.

2024-12-17 16:15 UTC, pacifikus requested changes
Добрый день!

Спасибо за работу! В целом все отлично! При проверке пока ограничилась только частью, которая требовалась в ДЗ 1.

Если честно, тоже не очень поняла идею с 14 и 21 днями - получается, что была коммуникация с клиентом, потом мы ждем 21 день и смотрим, оформил он карту или нет. Если оформил, то почему-то берем граф звонков за 14 дней? не очень понятен смысл этого, если у вас есть триггерное взаимодействие за 21 день до оформления, которое потенциально и могло привести к оформлению, зачем смотреть граф более позднего периода? Или граф берется за 14 дней до даты коммуникации?

2024-12-17 16:15 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +  - Задача состоит в обучении классификатора Catboost на наиболее важных фичах. Данный классификатор выбран ввиду его универсальности при работе с данными, что позволит существенно сократить время и
А как именно определяются наиболее важные фичи?

2024-12-17 16:15 UTC, pacifikus commented on docs/ml_system_design_doc.md
> +  - Создать инструмент, который будет предсказывать наиболее склонных к оформлению кредитных карт клиентов банка в малоизученном пользовательском сегменте. Это позволит:
Правильно ли я понимаю, что модель "ищет" сегмент клиентов банка, которые склонны к оформлению кредитной карты после рекламной коммуникации с ними? Если так, то задача походит скорее на uplift-моделирование

2024-12-18 08:31 UTC, Uberwald commented on docs/ml_system_design_doc.md
> +  - Задача состоит в обучении классификатора Catboost на наиболее важных фичах. Данный классификатор выбран ввиду его универсальности при работе с данными, что позволит существенно сократить время и
Фичи отбираются с помощью внутренней библиотеки МТС - emergent.

2024-12-18 08:34 UTC, Uberwald commented on docs/ml_system_design_doc.md
> +  - Создать инструмент, который будет предсказывать наиболее склонных к оформлению кредитных карт клиентов банка в малоизученном пользовательском сегменте. Это позволит:
Не совсем. Под сегментом подразумевался сегмент неабонентов. По таким людям в целом мало моделей в МТС Digital, поэтому для нас это новый сегмент. Коллеги из Банка, очевидно, работают в нём, но у них нет данных мобильного оператора. Новизна проекта как раз и заключается в том, что мы пытаемся исследовать сегмент с помощью новых данных, недоступных Банку.

2024-12-18 08:45 UTC, Uberwald commented
> Добрый день!
> 
> Спасибо за работу! В целом все отлично! При проверке пока ограничилась только частью, которая требовалась в ДЗ 1.
> 
> Если честно, тоже не очень поняла идею с 14 и 21 днями - получается, что была коммуникация с клиентом, потом мы ждем 21 день и смотрим, оформил он карту или нет. Если оформил, то почему-то берем граф звонков за 14 дней? не очень понятен смысл этого, если у вас есть триггерное взаимодействие за 21 день до оформления, которое потенциально и могло привести к оформлению, зачем смотреть граф более позднего периода? Или граф берется за 14 дней до даты коммуникации?

Всё верно, звонки берутся за 14 дней до даты коммуникации. Идея в том, что за две недели до бизнес даты (даты коммуникации, если человек не оформил кредитную карту (таргет «0») и даты «контракта», если оформил (таргет «1»)) мы получим признаки, присущие тому или иному классу. Что-то вроде: «За две недели до оформление кредитной карты наши клиенты Банка созваниваются с абонентами МТС в n раз чаще». Естественно, тут стоит добавить именно банковские признаки, вроде наличия задолженностей, оформленных КК и прочего, но пока передо мной поставлена задача выдать все возможное по данным мобильного оператора.

2024-12-24 12:21 UTC, pacifikus approved these changes
Добрый день!

Спасибо за работу и комментарии! Теперь поняла идею, все выглядит отлично!

2024-12-24 12:47 UTC, merged